name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Lint PHP files
      run: find . -type f -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
    
    - name: Check code style
      run: vendor/bin/phpcs --standard=Generic --ignore="*/vendor/*" .

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug
    
    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        npm ci
    
    - name: Run tests
      run: vendor/bin/phpunit
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
